name: Build & publish
on: {push: {branches: [master]}, pull_request: {branches: [master]}, workflow_dispatch}

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    steps:
    - uses: twojstaryzdomu/checkout@HEAD
      with:
        fetch-depth: '0'
      env:
        COPY_FILES: '~/.ssh/config_github ~/.ssh/id_rsa_github'
    - id: debianise
      uses: twojstaryzdomu/debianise@HEAD
      with:
        create_changelog: true
        install_build_depends: false
        debug: true
    - id: action-gh-release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ steps.debianise.outputs.files }}
        name: ${{ steps.debianise.outputs.release_name }}
        tag_name: ${{ steps.debianise.outputs.tag_name }}
        fail_on_unmatched_files: true
        draft: true
        prerelease: true
